#:kivy 2.1.0

<VisualNode>:
    size_hint: (None, None)
    size: (50, 50)
    background_color: 1, 1, 1, 0
    color: 1, 1, 1, 1
    button_color: 0.4, 0.7, 0.4, .4
    border_color: 0.7, 0.7, 0.2, 1
    canvas:
        Color:
            rgba: self.button_color
        Rectangle:
            size: self.size
            pos: self.pos
        Color:
            rgba: self.border_color
        Line:
            width: 2
            rectangle: self.x, self.y, self.width, self.height



    